components:
  x-stackQL-resources:
    clusters:
      name: clusters
      methods:
        create_cluster:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.CreateCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_cluster:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.DeleteCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        describe_clusters:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.DescribeClusters/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        initialize_cluster:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.InitializeCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        modify_cluster:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.ModifyCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      id: aws.cloudhsmv2.clusters
      sqlVerbs:
        delete:
          - $ref: '#/components/x-stackQL-resources/clusters/methods/delete_cluster'
        insert:
          - $ref: '#/components/x-stackQL-resources/clusters/methods/create_cluster'
        select:
          - $ref: >-
              #/components/x-stackQL-resources/clusters/methods/describe_clusters
        update: []
      title: clusters
    hsm:
      name: hsm
      methods:
        create_hsm:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.CreateHsm/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_hsm:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.DeleteHsm/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      id: aws.cloudhsmv2.hsm
      sqlVerbs:
        delete:
          - $ref: '#/components/x-stackQL-resources/hsm/methods/delete_hsm'
        insert:
          - $ref: '#/components/x-stackQL-resources/hsm/methods/create_hsm'
        select: []
        update: []
      title: hsm
    backups:
      name: backups
      methods:
        copy_backup_to_region:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.CopyBackupToRegion/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_backup:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.DeleteBackup/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        describe_backups:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.DescribeBackups/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        modify_backup_attributes:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.ModifyBackupAttributes/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        restore_backup:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.RestoreBackup/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      id: aws.cloudhsmv2.backups
      sqlVerbs:
        delete:
          - $ref: '#/components/x-stackQL-resources/backups/methods/delete_backup'
        insert: []
        select:
          - $ref: '#/components/x-stackQL-resources/backups/methods/describe_backups'
        update: []
      title: backups
    tags:
      name: tags
      methods:
        list_tags:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.ListTags/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        tag_resource:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.TagResource/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        untag_resource:
          operation:
            $ref: '#/paths//#X-Amz-Target=BaldrApiService.UntagResource/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      id: aws.cloudhsmv2.tags
      sqlVerbs:
        delete: []
        insert: []
        select:
          - $ref: '#/components/x-stackQL-resources/tags/methods/list_tags'
        update: []
      title: tags
