components:
  x-stackQL-resources:
    resources:
      name: resources
      methods:
        createcluster_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.CreateCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deletecluster_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.DeleteCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        describeclusters_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.DescribeClusters/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        initializecluster_resource:
          operation:
            $ref: >-
              #/paths/%2F%23X-Amz-Target%3DBaldrApiService.InitializeCluster/post
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        modifycluster_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.ModifyCluster/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createhsm_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.CreateHsm/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deletehsm_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.DeleteHsm/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        copybackuptoregion_resource:
          operation:
            $ref: >-
              #/paths/%2F%23X-Amz-Target%3DBaldrApiService.CopyBackupToRegion/post
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deletebackup_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.DeleteBackup/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        describebackups_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.DescribeBackups/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        modifybackupattributes_resource:
          operation:
            $ref: >-
              #/paths/%2F%23X-Amz-Target%3DBaldrApiService.ModifyBackupAttributes/post
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        restorebackup_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.RestoreBackup/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        listtags_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.ListTags/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.ResourceDescriptions
        tagresource_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.TagResource/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        untagresource_resource:
          operation:
            $ref: '#/paths/%2F%23X-Amz-Target%3DBaldrApiService.UntagResource/post'
          request:
            mediaType: application/x-amz-json-1.0
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      id: aws.cloud_control.resources
      sqlVerbs:
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/deletecluster_resource
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/deletehsm_resource
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/deletebackup_resource
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/createcluster_resource
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/createhsm_resource
        select:
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/describeclusters_resource
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/describebackups_resource
          - $ref: >-
              #/components/x-stackQL-resources/resources/methods/listtags_resource
        update: []
      title: resources
